# Generated by Django 5.1.1 on 2024-11-13 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Carmen', max_length=50, null=True)),
                ('AboutHeadLine1', models.CharField(max_length=1000)),
                ('AboutHeadLine2', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutHeadLine3', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutHeadLine4', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutHeadLine5', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailHead1', models.CharField(max_length=1000)),
                ('AboutDetailHead2', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailHead3', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailHead4', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailHead5', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailLine1', models.CharField(max_length=1000)),
                ('AboutDetailLine2', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailLine3', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailLine4', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutDetailLine5', models.CharField(blank=True, max_length=1000, null=True)),
                ('Proprietorship1', models.CharField(blank=True, max_length=1000, null=True)),
                ('Proprietorship2', models.CharField(blank=True, max_length=1000, null=True)),
                ('AboutLogoImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Carmen', max_length=50, null=True)),
                ('NameLine1', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Some special characters like (~!#^`'$|{}<>*) are not allowed.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')])),
                ('NameLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('NameLine3', models.CharField(blank=True, max_length=50, null=True)),
                ('NameLine4', models.CharField(blank=True, max_length=50, null=True)),
                ('NameLine5', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressLine1', models.CharField(max_length=50)),
                ('AddressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressLine3', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressLine4', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressLine5', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressCity', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Some special characters like (~!#^`'$|{}<>*) are not allowed.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')])),
                ('AddressPinCode', models.CharField(max_length=50)),
                ('AddressPhone1', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number +91 9999999999', regex='^(\\+\\d{1,3})?\\d{10}$')])),
                ('AddressPhone2', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number +91 9999999999', regex='^(\\+\\d{1,3})?\\d{10}$')])),
                ('AddressEmailId', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Please enter valid Email address.', regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')])),
                ('AddressCustomerCarePh', models.CharField(blank=True, max_length=50, null=True)),
                ('LocationMapLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('YoutubeLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('FaceBookLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('InstagramLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('TwitterLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('WhatsappLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('LinkedinLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('OtherSNLink1', models.CharField(blank=True, max_length=1000, null=True)),
                ('OtherSNLink2', models.CharField(blank=True, max_length=1000, null=True)),
                ('OtherSNLink3', models.CharField(blank=True, max_length=1000, null=True)),
                ('SloganLine1', models.CharField(blank=True, max_length=1000, null=True)),
                ('SloganLine2', models.CharField(blank=True, max_length=1000, null=True)),
                ('SloganLine3', models.CharField(blank=True, max_length=1000, null=True)),
                ('LogoImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Carmen', max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Please enter valid Email address.', regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')])),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number +91 9999999999', regex='^(\\+\\d{1,3})?\\d{10}$')])),
                ('is_Satisfied', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='HomepageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescriptionHeading', models.CharField(max_length=500)),
                ('DescriptionLine1', models.CharField(blank=True, max_length=1000, null=True)),
                ('DescriptionLine2', models.CharField(blank=True, max_length=1000, null=True)),
                ('DescriptionLine3', models.CharField(blank=True, max_length=1000, null=True)),
                ('DescriptionImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Some special characters like (~!#^`'$|{}<>*) are not allowed.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Some special characters like (~!#^`'$|{}<>*) are not allowed.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')])),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Penddng', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='PENDING', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.product')),
            ],
        ),
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Some special characters like (~!#^`'$|{}<>*) are not allowed.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')])),
                ('qty', models.IntegerField(default=0, max_length=6)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name='price')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sizes')),
            ],
        ),
    ]
